---
# The following environmental variables are required:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_SSH_KEY_ID
#
# @group_id and @subnet_id are created from names defined
# in the aws-name-to-id.rb file. To change the names, edit
# the file or set the following environment variables:
# - AWS_REGION
# - AWS_SECURITY_GROUP
# - AWS_SUBNET

<% require_relative 'aws-name-to-id' %>

driver:
  name: ec2
  instance_type: t2.micro # Free tier instance
  associate_public_ip: true
  region: <%= @region %>
  availability_zone: <%= @availability_zone %>
  security_group_ids: [<%= @group_id %>]
  subnet_id: <%= @subnet_id %>

transport:
  ssh_key: <%= ENV['HOME'] %>/.ssh/id_rsa

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
    driver:
      image_id: ami-1255b321
    transport:
      username: centos
  - name: windows-2012r2
    driver:
      image_id: ami-71876711

suites:
  - name: default
    run_list:
      - recipe[rundeck-node]
