---
# The following environmental variables are required:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_SSH_KEY_ID
#
# @group_id and @subnet_id are created from names defined
# in the aws-name-to-id.rb file. To change the names, edit
# the file or set the following environment variables:
# - AWS_REGION
# - AWS_SECURITY_GROUP
# - AWS_SUBNET

<% require_relative 'aws-name-to-id' %>

driver:
  name: ec2
  region: us-west-2
  availability_zone: us-west-2a
  instance_type: t2.micro # Free tier instance
  associate_public_ip: true
  security_group_ids: [<%= @group_id %>]
  subnet_id: <%= @subnet_id %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6
    driver:
      image_id: ami-1255b321
    transport:
      username: centos

suites:
  - name: default
    run_list:
      - recipe[rundeck-node]
    attributes:

# Example Windows platform
#
# - name: windows-2008r2
#   driver_plugin: vagrant_winrm
#   provisioner:
#     name:                 chef_zero
#     sudo:                 false
#     require_chef_omnibus: false
#     root_path:            C:/var/chef
#     chef_client_path:     C:/opscode/chef/bin/chef-client
#     chef_omnibus_root:    C:/opscode/chef/
#     ruby_bindir:          C:/opscode/chef/embedded/bin
#   driver_config:
#     provision: true
#     custom_settings:
#       omnibus.chef_version: '11.16.4'
#     box:     <boxname>
#     box_url: <boxurl>
#
# Please check OS X's EULA before enabling it
#
# - name: osx-10
#   driver_plugin: vagrant
#   driver_config:
#     box:     osx-yosemite-0.2.0
#     box_url: http://files.dryga.com/boxes/osx-yosemite-0.2.0.box
