language: ruby
cache: bundler
rvm:
- 2.0.0
sudo: false
deploy:
  edge: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Process Management
  client_key: ".travis/client.pem"
  on:
    tags: true
    all_branches: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_2f4029ef94a3_key -iv $encrypted_2f4029ef94a3_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
